apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "keyless-cosign-check"
  annotations:
    cert-manager.io/inject-ca-from: cosign-keyless-github-admission-webhook/cosign-keyless-github-admission-webhook
webhooks:
- name: "subject.cosign.sigstore"
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - kube-system
      - kube-public
      - hnc-system
      - kube-node-lease
      - cosign-keyless-github-admission-webhook
      - cert-manager
  rules:
  - apiGroups:   [""]
    apiVersions: ["v1"]
    operations:  ["CREATE"]
    resources:   ["pods"]
    scope:       "Namespaced"
  clientConfig:
    # url: https://cooocoo.loca.lt
    # caBundle: k get configmaps -n kube-system kube-root-ca.crt -o jsonpath='{.data.ca\.crt}' | base64
    # LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1UQXhOVEUwTXpZMU0xb1hEVE14TVRBeE16RTBNelkxTTFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTHY1CkFjK0JuR0pmcElod0pTem5OYmpubEpaU3JyK2M1djVEYjMvTXhmMWs1ZFBuVUs0eTZpT0dBODBGejRlV2QyZWQKWnBrKytYbWFQd3NldGVvQWprbkJTQnNSYXozMzZpaXBPK01lbEdQbDlaZm1tdHVnYk9VMlUxRzdPNkc1V2VVTwppci9ua0oyVkZ1cmdaZ29ya1BkbkVBcEVLVStYdm9wcFhzdTBHdVI1NEdjalhmSkdaeG85ZmVGQ1dLam4rZGs1CnZ2LzFYTksrMlZYZnF3TVd1ZUFWbjUvQ3AvSzNuNlZabGhlUXpSWld6U2Z4Zk1ydGEva2V6azlUUmVacWYxQnMKNCsvRXhVcVJBT3VUb0pBb0JQRElweWpURm9UWVg0ZTByYVg3ZWFsNmVmV21ySWZpYTJ2akY3NTZPUzA2MDhCYgpqeHAwVmpYNGhHc3RHQk5hWkhVQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZPMVBMRzA2ZzRkMlFtakM3QTBFSUpUbTY2M0VNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFCQWlyemszcHYrWFZGVHFFa2xVSnJ5TWp0NEhXOWFiZjhwdUhMZWtvbmZaWUlSelozTApSM29FU28yRVRYZW5VR242dTh6ZHloOExQdWxYUlQwekhNK0FldkROOW9FcFpKb3RGYnFiMEY3MjYwNmZkUWplCmh6WmMvMFhXdXFTT05rUkFpSlFNZWRaT1lKQ1ZmTGw5ejEvcXY4S0UvTFZhdm5HVERPU1RaWjVreTA0Sm1Wd0kKSVBmUk80RWdnQzhLN2c4cEpmaVQ4RGRtWkJmTno0Ty8ySXd3WGRvTXoxalJEQ0tBZjQzZFVLTWg0emFVeWlGKwpQY0s0RXAxVjBTd0tadTZGSk5vVGlOYXpZN2kvRTdrUTk4ZHJWUVlQWDBIZTh6cUZPbWNqMWh1d0lrNzhZcGd6Ckl6OHcxcXZiWG8rcWtRQTQ1am91UHVCeFk4Z1UxZVNCNFY5TAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==

    service:
      namespace: "cosign-keyless-github-admission-webhook"
      name: "cosign-keyless-github-admission-webhook"
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  timeoutSeconds: 15
