name: Build

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: none
      checks: none
      contents: none
      deployments: none
      issues: none
      packages: write
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
      id-token: none

    steps:
      - uses: actions/checkout@v2.3.5

      - name: Login to dockerhub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1.10.0
        with:
          username: chrisns
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: docker_meta
        uses: docker/metadata-action@v3.6.0
        with:
          images: |
            ${{ github.repository }}
            ghcr.io/${{ github.repository }}
          flavor: |
            latest=true
          tags: |
            type=sha,format=long
            type=edge,branch=$repo.default_branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: build+load
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Create kind cluster
        uses: helm/kind-action@2a525709fd0874b75d7ae842d257981b0e0f557d
        timeout-minutes: 5
        with: 
          kubectl_version: v1.22.2
          cluster_name: kind

      - name: Install kustomize
        run: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash

      - name: Load our docker image into kind cluster
        run: kind load docker-image $(echo "${{ steps.docker_meta.outputs.tags }}" | head -1)

      - name: Set imagetag with kustomize
        run: kustomize edit set image ghcr.io/chrisns/cosign-keyless-admission-webhook=$(echo "${{ steps.docker_meta.outputs.tags }}" | head -1) 

      - name: Install cert-manager
        run: |
          kubectl apply -f https://github.com/jetstack/cert-manager/releases/latest/download/cert-manager.yaml
          kubectl wait --for=condition=available --timeout=600s  -n cert-manager \
            deployment/cert-manager \
            deployment/cert-manager-cainjector \
            deployment/cert-manager-webhook

      - name: Install our validating webhook
        run: |
          kustomize build | kubectl apply -f -
          kubectl wait --for=condition=available --timeout=600s deployment/cosign-keyless-admission-webhook -n cosign-keyless-admission-webhook

      - name: Deploy known bad issuer pod
        run: "! kubectl apply -f test/BadIssuer.yaml"

      - name: Deploy known bad subject pod
        run: "! kubectl apply -f test/BadSubject.yaml"

      - name: Deploy known good pod
        run: kubectl apply -f test/GoodMixed.yaml

      - name: push
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=gha
          push: true
          cache-to: type=gha,mode=max

    outputs:
      tags: ${{ steps.docker_meta.outputs.tags }}

  sign:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    permissions:
      actions: none
      checks: none
      contents: none
      deployments: none
      issues: none
      packages: write
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
      id-token: write

    steps:
      - name: Login to dockerhub
        uses: docker/login-action@v1.10.0
        with:
          username: chrisns
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: sigstore/cosign-installer@v1.2.1

      - name: Sign the images
        run: cosign sign ${TAGS}
        env:
          TAGS: ${{needs.build.outputs.tags}}
          COSIGN_EXPERIMENTAL: 1
